// Code generated by protoc-gen-go. DO NOT EDIT.
// source: praefect/mock/mock.proto

package mock

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	empty "github.com/golang/protobuf/ptypes/empty"
	gitalypb "gitlab.com/gitlab-org/gitaly/proto/go/gitalypb"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type SimpleRequest struct {
	Value                int32    `protobuf:"varint,1,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SimpleRequest) Reset()         { *m = SimpleRequest{} }
func (m *SimpleRequest) String() string { return proto.CompactTextString(m) }
func (*SimpleRequest) ProtoMessage()    {}
func (*SimpleRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d20d83172fd49eb0, []int{0}
}

func (m *SimpleRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SimpleRequest.Unmarshal(m, b)
}
func (m *SimpleRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SimpleRequest.Marshal(b, m, deterministic)
}
func (m *SimpleRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SimpleRequest.Merge(m, src)
}
func (m *SimpleRequest) XXX_Size() int {
	return xxx_messageInfo_SimpleRequest.Size(m)
}
func (m *SimpleRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SimpleRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SimpleRequest proto.InternalMessageInfo

func (m *SimpleRequest) GetValue() int32 {
	if m != nil {
		return m.Value
	}
	return 0
}

type SimpleResponse struct {
	Value                int32    `protobuf:"varint,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SimpleResponse) Reset()         { *m = SimpleResponse{} }
func (m *SimpleResponse) String() string { return proto.CompactTextString(m) }
func (*SimpleResponse) ProtoMessage()    {}
func (*SimpleResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d20d83172fd49eb0, []int{1}
}

func (m *SimpleResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SimpleResponse.Unmarshal(m, b)
}
func (m *SimpleResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SimpleResponse.Marshal(b, m, deterministic)
}
func (m *SimpleResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SimpleResponse.Merge(m, src)
}
func (m *SimpleResponse) XXX_Size() int {
	return xxx_messageInfo_SimpleResponse.Size(m)
}
func (m *SimpleResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SimpleResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SimpleResponse proto.InternalMessageInfo

func (m *SimpleResponse) GetValue() int32 {
	if m != nil {
		return m.Value
	}
	return 0
}

type RepoRequest struct {
	Repo                 *gitalypb.Repository `protobuf:"bytes,1,opt,name=repo,proto3" json:"repo,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *RepoRequest) Reset()         { *m = RepoRequest{} }
func (m *RepoRequest) String() string { return proto.CompactTextString(m) }
func (*RepoRequest) ProtoMessage()    {}
func (*RepoRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d20d83172fd49eb0, []int{2}
}

func (m *RepoRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RepoRequest.Unmarshal(m, b)
}
func (m *RepoRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RepoRequest.Marshal(b, m, deterministic)
}
func (m *RepoRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RepoRequest.Merge(m, src)
}
func (m *RepoRequest) XXX_Size() int {
	return xxx_messageInfo_RepoRequest.Size(m)
}
func (m *RepoRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RepoRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RepoRequest proto.InternalMessageInfo

func (m *RepoRequest) GetRepo() *gitalypb.Repository {
	if m != nil {
		return m.Repo
	}
	return nil
}

func init() {
	proto.RegisterType((*SimpleRequest)(nil), "mock.SimpleRequest")
	proto.RegisterType((*SimpleResponse)(nil), "mock.SimpleResponse")
	proto.RegisterType((*RepoRequest)(nil), "mock.RepoRequest")
}

func init() { proto.RegisterFile("praefect/mock/mock.proto", fileDescriptor_d20d83172fd49eb0) }

var fileDescriptor_d20d83172fd49eb0 = []byte{
	// 262 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x8f, 0xc1, 0x4a, 0xc3, 0x30,
	0x18, 0xc7, 0x49, 0xe9, 0x86, 0x64, 0x2a, 0x2e, 0x88, 0x8c, 0x7a, 0x91, 0x82, 0xb2, 0xc3, 0x48,
	0x61, 0x1e, 0x3d, 0x29, 0xcc, 0x9b, 0x97, 0x0e, 0x1f, 0x20, 0x8b, 0xdf, 0x6a, 0x30, 0xed, 0x17,
	0x93, 0x74, 0xd0, 0x27, 0xd1, 0x93, 0x8f, 0xe3, 0x43, 0x79, 0x92, 0xa4, 0x16, 0x77, 0xde, 0x25,
	0x7c, 0xdf, 0x3f, 0x3f, 0xfe, 0xc9, 0x8f, 0xce, 0x8c, 0x15, 0xb0, 0x05, 0xe9, 0x8b, 0x1a, 0xe5,
	0x5b, 0x3c, 0xb8, 0xb1, 0xe8, 0x91, 0xa5, 0x61, 0xce, 0x8e, 0xdd, 0xab, 0xb0, 0xf0, 0xd2, 0x67,
	0x19, 0xd5, 0xaa, 0xf1, 0x7f, 0xf3, 0x65, 0x85, 0x58, 0x69, 0x28, 0xe2, 0xb6, 0x69, 0xb7, 0x05,
	0xd4, 0xc6, 0x77, 0xfd, 0x65, 0x7e, 0x4d, 0x4f, 0xd6, 0xaa, 0x36, 0x1a, 0x4a, 0x78, 0x6f, 0xc1,
	0x79, 0x76, 0x4e, 0x47, 0x3b, 0xa1, 0x5b, 0x98, 0x91, 0x2b, 0x32, 0x1f, 0x95, 0xfd, 0x92, 0xdf,
	0xd0, 0xd3, 0x01, 0x73, 0x06, 0x1b, 0x07, 0xff, 0x5c, 0xb2, 0xcf, 0xdd, 0xd1, 0x49, 0x09, 0x06,
	0x87, 0xb2, 0x05, 0x4d, 0x2d, 0x18, 0x8c, 0x5d, 0x93, 0x25, 0xe3, 0x95, 0xf2, 0x42, 0x77, 0x3c,
	0x20, 0x4e, 0x79, 0xb4, 0xdd, 0x43, 0xfa, 0xf9, 0xbd, 0x20, 0x65, 0xa4, 0x96, 0x5f, 0x64, 0xf8,
	0xcc, 0x1a, 0xec, 0x4e, 0x49, 0x60, 0x8f, 0x74, 0x1a, 0xd8, 0x7b, 0x29, 0xc1, 0x39, 0xb4, 0xcf,
	0x8d, 0xb0, 0x1d, 0x9b, 0xf2, 0x28, 0xbf, 0xf7, 0x4e, 0x76, 0xc1, 0x7b, 0x47, 0x3e, 0x38, 0xf2,
	0x55, 0x70, 0xcc, 0xc7, 0x3f, 0x1f, 0xf3, 0xe4, 0x28, 0x61, 0x2b, 0x7a, 0x16, 0xf0, 0xa7, 0xd6,
	0x0b, 0x7f, 0x70, 0x0d, 0xd9, 0x8c, 0x63, 0x7e, 0xfb, 0x1b, 0x00, 0x00, 0xff, 0xff, 0xdd, 0xab,
	0x58, 0x75, 0x8c, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// SimpleServiceClient is the client API for SimpleService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type SimpleServiceClient interface {
	// RepoAccessorUnary is a unary RPC that accesses a repo
	RepoAccessorUnary(ctx context.Context, in *RepoRequest, opts ...grpc.CallOption) (*empty.Empty, error)
	// RepoMutatorUnary is a unary RPC that mutates a repo
	RepoMutatorUnary(ctx context.Context, in *RepoRequest, opts ...grpc.CallOption) (*empty.Empty, error)
}

type simpleServiceClient struct {
	cc *grpc.ClientConn
}

func NewSimpleServiceClient(cc *grpc.ClientConn) SimpleServiceClient {
	return &simpleServiceClient{cc}
}

func (c *simpleServiceClient) RepoAccessorUnary(ctx context.Context, in *RepoRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/mock.SimpleService/RepoAccessorUnary", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *simpleServiceClient) RepoMutatorUnary(ctx context.Context, in *RepoRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/mock.SimpleService/RepoMutatorUnary", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SimpleServiceServer is the server API for SimpleService service.
type SimpleServiceServer interface {
	// RepoAccessorUnary is a unary RPC that accesses a repo
	RepoAccessorUnary(context.Context, *RepoRequest) (*empty.Empty, error)
	// RepoMutatorUnary is a unary RPC that mutates a repo
	RepoMutatorUnary(context.Context, *RepoRequest) (*empty.Empty, error)
}

// UnimplementedSimpleServiceServer can be embedded to have forward compatible implementations.
type UnimplementedSimpleServiceServer struct {
}

func (*UnimplementedSimpleServiceServer) RepoAccessorUnary(ctx context.Context, req *RepoRequest) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RepoAccessorUnary not implemented")
}
func (*UnimplementedSimpleServiceServer) RepoMutatorUnary(ctx context.Context, req *RepoRequest) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RepoMutatorUnary not implemented")
}

func RegisterSimpleServiceServer(s *grpc.Server, srv SimpleServiceServer) {
	s.RegisterService(&_SimpleService_serviceDesc, srv)
}

func _SimpleService_RepoAccessorUnary_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RepoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SimpleServiceServer).RepoAccessorUnary(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mock.SimpleService/RepoAccessorUnary",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SimpleServiceServer).RepoAccessorUnary(ctx, req.(*RepoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SimpleService_RepoMutatorUnary_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RepoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SimpleServiceServer).RepoMutatorUnary(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mock.SimpleService/RepoMutatorUnary",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SimpleServiceServer).RepoMutatorUnary(ctx, req.(*RepoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _SimpleService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "mock.SimpleService",
	HandlerType: (*SimpleServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RepoAccessorUnary",
			Handler:    _SimpleService_RepoAccessorUnary_Handler,
		},
		{
			MethodName: "RepoMutatorUnary",
			Handler:    _SimpleService_RepoMutatorUnary_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "praefect/mock/mock.proto",
}
