#!/usr/bin/env ruby

# This file was placed here by GitLab. It makes sure that your pushed commits
# will be processed properly.

ref_name  = ARGV[0]
old_value = ARGV[1]
new_value = ARGV[2]
repo_path = Dir.pwd
gl_id    = ENV.delete('GL_ID')

require_relative '../lib/gitlab_custom_hook'

# This is a workaround for NFS-mounted directories. Before we update the
# ref, be sure we open and close the directory that contains the loose
# ref to flush the attribute cache. This ensures we see a loose ref if
# it were created recently.
if ref_name&.start_with?("refs/")
  begin
    ref_path = File.dirname(ref_name)
    dir = Dir.open(File.join(repo_path, ref_path))
    dir.close if dir
  rescue
    # Do nothing if the directory doesn't exist or some other error happens
  end
end

if GitlabCustomHook.new(repo_path, gl_id).update(ref_name, old_value, new_value)
  exit 0
else
  exit 1
end
